environment:
  matrix:
    - job_name: Windows
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019

    - job_name: Linux
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu

    - job_name: macOS
      APPVEYOR_BUILD_WORKER_IMAGE: macOS

matrix:
  fast_finish: true

for:

# ======================================
#      Windows
# ======================================

-
  matrix:
    only:
    - job_name: Windows

  init:
  - echo "Init for Windows"
  - cmd: python -m pip install pyinstaller

  build_script:
  - cmd: pyinstaller --onefile app.py

  artifacts:
  - path: speedreader.exe

  test: off

# ======================================
#      Linux
# ======================================

-
  matrix:
    only:
    - job_name: Linux

  init:
  - echo "Init for Linux"
  - sh: pip install pyinstaller

  build_script:
  - sh: pyinstaller --onefile app.py

  artifacts:
  - path: dist/speedreader_l

  test: off

# ======================================
#      macOS
# ======================================

-
  matrix:
    only:
    - job_name: macOS

  init:
  - echo "Init for macOS"
  - sh: pip install pyinstaller

  build_script:
  - sh: pyinstaller --onefile app.py

  artifacts:
  - path: dist/speedreader_ios

  test: off
