environment:
  matrix:
    - job_name: Windows
      QTDIR: C:\Qt\5.10.1\msvc2017_64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019

    - job_name: Linux
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu

    - job_name: macOS
      APPVEYOR_BUILD_WORKER_IMAGE: macOS

matrix:
  fast_finish: true
  
for:
  
# ======================================
#      Windows
# ======================================

-
  matrix:
    only:
    - job_name: Windows

  init:
  - echo "Init for Windows"

  build_script:
  - echo "Build for Windows"

  test: off

# ======================================
#      Linux
# ======================================

-
  matrix:
    only:
    - job_name: Linux

  init:
  - echo "Init for Linux"

  build_script:
  - echo "Build for Linux"

  test: off

# ======================================
#      macOS
# ======================================

-
  matrix:
    only:
    - job_name: macOS

  init:
  - echo "Init for macOS"

  build_script:
  - echo "Build for macOS"

  test: off